#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No ES_HOME provided, not starting performance-analyzer-agent"
else

    if ! echo $* | grep -E '(^-d |-d$| -d |--daemonize$|--daemonize )' > /dev/null; then
        java -Des.path.home=$1 -Dlog4j.configurationFile=$1/plugins/performance-analyzer/pa_config/log4j2.xml \
                -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 \
                -XX:InitialBootClassLoaderMetaspaceSize=30720 -XX:MaxRAM=400m \
                -Dlog4j.configurationFile=$1/plugins/performance-analyzer/pa_config/log4j2.xml \
                -cp $1/lib/*:$1/plugins/performance-analyzer/* com.amazon.opendistro.performanceanalyzer.PerformanceAnalyzerApp
    else
        echo 'Starting deamon'
        java -Des.path.home=$1 -Dlog4j.configurationFile=$1/plugins/performance-analyzer/pa_config/log4j2.xml \
                -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 \
                -XX:InitialBootClassLoaderMetaspaceSize=30720 -XX:MaxRAM=400m \
                -Dlog4j.configurationFile=$1/plugins/performance-analyzer/pa_config/log4j2.xml \
                -cp $1/lib/*:$1/plugins/performance-analyzer/* com.amazon.opendistro.performanceanalyzer.PerformanceAnalyzerApp &> /dev/null &

        pid=$!
        PID_LOC=/tmp/performance-analyzer-agent
        if [ -n "$3" ]; then
            PID_LOC=$3
        fi

        if ! ps -p $pid > $PID_LOC ; then
            exit 1
        fi
    fi
fi